### ISSUE TITLE
请问那个ahk在哪？

### ISSUE THREAD

**Issue by larfchan** [WarmWine9/ConsChinese#1]
作者您好，请问您readme中提及的ahk文件在哪里？

**Comment by WarmWine9** [comment]
在界面的右边有一个 release, ahk 和 exe 都在那里。


Larf Chan ***@***.***>于2024年1月1日 周一21:29写道：

**Comment by larfchan** [comment]
您的邮件已经收到！I have received your email!LarfChan
--------------------------------------------------------------
上面是邮件的自动回复。我看到了您的ahk和exe，谢谢作者！
